### ISSUE TITLE
Minor site issues

### ISSUE THREAD

**Issue by jzeferino** [jzeferino/AllGithubEmojis#5]
* [x] Made search non case sensitive
* [x] Add loading when loading page
* [x] Make button to go to top visible
* [x] Make emoji name font bigger
~~* [ ] Emoji label with two lines always~~
* [x] Remove empty titles when searching
* [x] Make github buttons in one [line](https://user-images.githubusercontent.com/10722952/32148543-9c50d0a6-bcf0-11e7-9d50-d101adb4c306.png)

**Comment by eliamartani** [comment]
created a branch `feature/gh-pages-fixes` for it.

**Comment by jzeferino** [comment]
Closed by #8
