### ISSUE TITLE
how to use it in Mac OS

### ISSUE THREAD

**Issue by kudumi** [jzeferino/AllGithubEmojis#9]
sorry for the noob question, how can I use them in mac?

**Comment by jzeferino** [comment]
You can go to https://jzeferino.github.io/AllGithubEmojis/ and click in any emoji and it will be copied to your clipboard. You can then paste it wherever you want. This emojis are specifically all the supported emojis in github but they are also supported in macOS.

**Comment by kudumi** [comment]
when I paste it my mac, I don't get the icon rather I just get ":grinning:". I have to right click the image and copy it from your website.

**Comment by jzeferino** [comment]
I tested it and pasted ":skier:" in slack for example and it worked. Where are you trying to paste?

**Comment by kudumi** [comment]
It does work in Slack and Discord but this is not system-wide, it can not work in web WhatsApp, Gmail compose (in the browser) or TextEdit. I thought we can set system-wide like this one https://github.com/warpling/Macmoji

please close this thread, thanks

**Comment by jzeferino** [comment]
So the goal if this project is to have a place were you can see all emojis supported on github. So everything that will support this emojis will be a plus.
